### ISSUE TITLE
Using options uid and gid for the user in devenv not working as expected

### ISSUE THREAD

**Issue by fjandrad** [diegoferigo/devenv#6]
From the conf.py it seems that the option user can either be a str or a dic, when trying to use it as a dic options entered were:
```
user: 
      name: "fjandrad"
      uid: "1001"
      gid: "1001"
```
Resulting in the following error

```
While processing 'user' element
Traceback (most recent call last):
  File "/home/fjandrad/.local/bin/devenv", line 33, in <module>
    sys.exit(load_entry_point('devenv==1.0', 'console_scripts', 'devenv')())
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/__main__.py", line 31, in main
    compose_yaml["services"][service], devenv_yaml[service])
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 30, in process
    compose_service = processor.process(option)
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 45, in process
    fcn()
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 58, in _process_user
    self._child_must_exist(user, "uid", int)
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 342, in _child_must_exist
    raise WrongOptionType(option, typeid)
devenv.exception.WrongOptionType: Expecting option 'uid' with type <class 'int'>
```

If inserted as ints as follows:

```
user: 
      name: "fjandrad"
      uid: 1001
      gid: 1001
```

Gives 
```
Traceback (most recent call last):
  File "/home/fjandrad/.local/bin/devenv", line 33, in <module>
    sys.exit(load_entry_point('devenv==1.0', 'console_scripts', 'devenv')())
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/__main__.py", line 31, in main
    compose_yaml["services"][service], devenv_yaml[service])
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 30, in process
    compose_service = processor.process(option)
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 45, in process
    fcn()
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 61, in _process_user
    uid = self._eval_in_shell(user["uid"])
  File "/home/fjandrad/.local/lib/python3.6/site-packages/devenv/conf.py", line 346, in _eval_in_shell
    cmd = os.path.expandvars(cmd)
  File "/usr/lib/python3.6/posixpath.py", line 288, in expandvars
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not int

```

Seems the error is related to the fact that it expects and `int` but then it is sent to the function `eval_in_shell` which uses the function `os.path.expandvars(cmd)`. This does not seem to work if the variable is and int while it seems is not a problem if its a str.

**Comment by fjandrad** [comment]
Changing 

```
uid = self._eval_in_shell(user["uid"])
gid = self._eval_in_shell(user["gid"])
```

to 

```
uid = user["uid"]
 gid = user["gid"]
```
Code lines 
https://github.com/diegoferigo/devenv/blob/1079f019048b5135b76314904a74073f6c1c97d8/devenv/conf.py#L60
https://github.com/diegoferigo/devenv/blob/1079f019048b5135b76314904a74073f6c1c97d8/devenv/conf.py#L61
Allows it to work although not sure if we are loosing something with this change. @diegoferigo

**Comment by diegoferigo** [comment]
Hi @fjandrad, thanks for reporting this issue. This is indeed a bug. I have some configurations that used the following:

```yaml
    user:
      name: "$(whoami)"
      uid: "$(id -u)"
      gid: "$(id -g)"
```

However passing explicitly the UID and GID was failing also on my setup. I opened #7 that should address the problem, let me know if it's ok. The PR will close this issue, feel free to open it again if the problem persists.
